Added note about installing gulp
I had gotten the following error when running the generator:
```
Last but not least, we'll set up style.css.



events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:998:11)
    at Process.ChildProcess._handle.onexit (child_process.js:789:34)
```
and it was because (duh) I didn't have Gulp installed. Just just a quick note to add it.

Thanks for this project/generator! :)